build:
  image: elixir:1.3
  environment:
    - MIX_ENV=test

  commands:
    - mix local.hex --force
    - mix deps.get
    - mix credo --strict
    - mix test

cache:
  mount:
    - .git
    - _build
    - deps

deploy:
  git_push:
    branch: master
    remote: dokku@xtian.us:dargobot
    force: false
    when:
      branch: master
